executors:
  nbcollection-builder:
    docker:
    - image: jbcurtin/nbcollection-builder
    resource_class: medium
    working_directory: ~/repo
jobs:
  Jdat Notebooks-Asdf Example:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: nbcollection-ci build-notebooks --collection-names jdat_notebooks
          --category-names asdf_example
        name: Build Jdat Notebooks-Asdf Example notebooks
        no_output_timeout: 60m
    - store_artifacts:
        path: /tmp/nbcollection-ci-artifacts
  Jdat Notebooks-Example Notebook:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: nbcollection-ci build-notebooks --collection-names jdat_notebooks
          --category-names example_notebook
        name: Build Jdat Notebooks-Example Notebook notebooks
        no_output_timeout: 60m
    - store_artifacts:
        path: /tmp/nbcollection-ci-artifacts
  Pull Request:
    executor:
    steps:
    - checkout
    - run:
        command: nbcollection-ci pull-request -u $CI_PULL_REQUEST
        name: Build Pull Request
        no_output_timeout: 60m
    - store_artifacts:
        path: /tmp/nbcollection-ci-artifacts

version: 2.1
workflows:
  Build:
    jobs:
    - Pull Request
    - Jdat Notebooks-Asdf Example
    - Jdat Notebooks-Example Notebook
  version: '2.1'
